---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: internaltableau
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: internaltableau
    spec:
      containers:
        - name: opensslsidekick
          image: quay.io/ukhomeofficedigital/dq-haproxy-openssl-sidekick:master
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
          env:
            - name: HOST
              value: '10.3.0.11'
            - name: PORT
              value: '8081'
          ports:
            - containerPort: 5000

        - name: proxy
          image: quay.io/ukhomeofficedigital/nginx-proxy
          securityContext:
            runAsNonRoot: true
          env:
            - name: PROXY_SERVICE_HOST
              value: 'http://127.0.0.1'
            - name: PROXY_SERVICE_PORT
              value: '5000'
            - name: LOG_FORMAT_NAME
              value: 'json'
            - name: NAXSI_USE_DEFAULT_RULES
              value: 'FALSE'
            - name: ENABLE_UUID_PARAM
              value: 'FALSE'
          ports:
            - name: https
              containerPort: 10443
