---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: internaltableau
  labels:
    stable.k8s.psg.io/kcm.class: default
  annotations:
    stable.k8s.psg.io/kcm.provider: http
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/whitelist-source-range: "{{.WHITELIST}}"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/secure-backends: "true"
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - {{ .URL }}
    secretName: internaltableau-tls
  rules:
  - host: {{ .URL }}
    http:
      paths:
      - backend:
          serviceName: internaltableau
          servicePort: https
        path: /
