---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: internaltableau
  labels:
    stable.k8s.psg.io/kcm.class: default
  annotations:
    stable.k8s.psg.io/kcm.provider: http
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/whitelist-source-range: "62.25.109.196/32, 80.169.158.34/32, 80.193.85.91/32, 86.188.197.170/29, 52.48.127.150/32, 52.48.127.151/32, 52.48.127.152/32, 52.48.127.153/32, 52.209.62.128/25, 52.56.62.128/25"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/secure-backends: "true"
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - {{ .URL }}
    secretName: internaltableau-tls
  rules:
  - host: {{ .URL }}
    http:
      paths:
      - backend:
          serviceName: internaltableau
          servicePort: https
        path: /
